spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: root
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 300ms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
minio:
  endpoint: http://localhost:9000
  bucketName: mall
  accessKey: minioadmin
  secretKey: minioadmin

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false