server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 300ms
  rabbitmq:
    host: localhost
    port: 15672
    virtual-host: /mall
    username: guest
    password: guest
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info
    com.macro.mall: debug